### ISSUE TITLE
sconsUtils patch does not apply cleanly

### ISSUE THREAD

**Issue by mjuric** [mjuric/conda-lsst#31]
From @mareuter's e-mail:

> The sconsUtils patch in the conda-lsst no longer applies cleanly at p0 when building against the w.2015.50 stack tag.

@mareuter is working on a fix.

**Comment by danielsf** [comment]
@mareuter I stumbled upon this bug (but not this issue) while trying to make the next conda release for lsst_sims.  I think I almost have it fixed.  What is your status (so that we don't step on each others' toes and enter merge conflict hell)?

**Comment by mjuric** [comment]
I rebased the [branch with the patch](https://github.com/lsst/sconsUtils/tree/u/mjuric/osx-deployment-target), and generated a new diff. That's on b7c79a5659d5acbf8be968691d682c2edb20fb10.

For future reference (me included): to get a conda-ready diff, you need to use the `--no-prefix` option with `git diff`. I.e., I generated this with:

```
$ git diff --no-prefix master > macosx-deployment-target.patch
```

(executed in `sconsUtils` working directory, with `u/mjuric/osx-deployment-target` checked out).
