### ISSUE TITLE
adding eupsforge.net/conda/dev as a channel raises an error

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#40]
Just running `conda config --add channels http://eupsforge.net/conda/dev` gives

`Error: Could not parse the yaml file. Use -f to use the
yaml parser (this will remove any structure or comments from the existing
.condarc file). Reason: couldn't parse modified yaml`

This can be avoided with `conda config --force --add channels http://eupsforge.net/conda/dev`, but the behavior seems odd.

**Comment by mjuric** [comment]
Did you have a hand-modified `~/.condarc`? I've seen similar errors when I'd modify it by hand and introduce mistakes.

Could you check if this is reproducible?

**Comment by danielsf** [comment]
I have never touched my .condarc

I have already experienced this problem both on my laptop and on lsst-dev.  Is there another test you would like me to perform?

**Comment by mjuric** [comment]
Can you give me steps to reproduce it? I'm failing miserably right now :(.

**Comment by danielsf** [comment]
it really is just

`conda config --add channels http://eupsforge.net/conda/dev`

my PATH is

/home/danielsf/conda-lsst/bin/:/home/danielsf/conda-lsst/miniconda/bin/:/opt/rh/devtoolset-3/root/usr/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/danielsf/bin

`which conda` is

~/conda-lsst/miniconda/bin/conda

and my .condarc is

channels:
- http://eupsforge.net/conda/dev_testing
- defaults

**Comment by rhiannonlynne** [comment]
For what it's worth, if I first remove the dev channel and then try to add
it again, I also get the error.

[ewok:~/lsstRepos/conda-lsst/miniconda] lynnej% conda config --remove
channels http://eupsforge.net/conda/dev --force
[ewok:~/lsstRepos/conda-lsst/miniconda] lynnej% more ~/.condarc
channels:
- defaults
  [ewok:~/lsstRepos/conda-lsst/miniconda] lynnej% conda config --add channels
  http://eupsforge.net/conda/dev
  Error: Could not parse the yaml file. Use -f to use the
  yaml parser (this will remove any structure or comments from the existing
  .condarc file). Reason: couldn't parse modified yaml
  [ewok:~/lsstRepos/conda-lsst/miniconda] lynnej%

However, if I then completely remove the ~/.condarc file and try to add it
the channel, it works.
[ewok:~/lsstRepos/conda-lsst/miniconda] lynnej% rm ~/.condarc
remove /Users/lynnej/.condarc? y
[ewok:~/lsstRepos/conda-lsst/miniconda] lynnej% conda config --add channels
http://eupsforge.net/conda/dev
[ewok:~/lsstRepos/conda-lsst/miniconda] lynnej%

-Lynne

**Comment by danielsf** [comment]
True: I also did not start seeing this error until I tried removing a channel with conda config --remove

**Comment by rhiannonlynne** [comment]
I think the 'remove' feature must be buggy. The fact that you have to use
--force in order to use it might be an indication.

**Comment by mjuric** [comment]
This is beginning to sound familiar -- I think @cwwalter encountered this as well (and we traced it to a bug in `conda config --remove`, and then I forgot about it). I'll open an issue with upstream.

**Comment by cwwalter** [comment]
Yes, that's correct.  I had to manually remove the file.

**Comment by mjuric** [comment]
Issue opened upstream: https://github.com/conda/conda/issues/2013

In the meantime, don't use `conda --remove` to manipulate `~/.condarc`; edit it by hand, if needed.
