### ISSUE TITLE
how to run `_build.sh` directly?

### ISSUE THREAD

**Issue by jhoblitt** [mjuric/conda-lsst#51]
I have the feeling that I'm missing something extremely obvious... when I try to run `_build.sh` directly, I get an error about missing parameters:

```
$ ./_build.sh build
eupspkg.main (fatal): PRODUCT, VERSION, or FLAVOR were not defined. refusing to proceed.
```

I have tried adding values for PREFIX & VERSION into the script, sourcing the eups config script, running `setup`, etc. all without any luck.  What is `build.sh` doing (that `_build.sh` does not) that I am missing?

**Comment by jhoblitt** [comment]
I believe this is the source of the failure:

https://github.com/RobertLuptonTheGood/eups/blob/09c2f84cf7b676192235774cbc7d8006a9d4bc86/lib/eupspkg.sh#L1091-L1093

**Comment by mjuric** [comment]
Yup, `_build.sh` was broken -- `EUPS_VERSION` wasn't dumped into it, so `VERSION=` would get passed to `eupspkg`. I've fixed it (in a more robust manner).

Reopen if the fix doesn't work.
