### ISSUE TITLE
Update the eups in the distribution to at least 2.0.1

### ISSUE THREAD

**Issue by cwwalter** [mjuric/conda-lsst#52]
There is a bug on OS X (at least on El Capitan) with the current version (1.5.9) of eups in the distribution.

```
wasabi:walter % setup boost
wasabi:walter % setup fftw
wasabi:walter % echo $LD_LIBRARY_PATH/
/Users/walter/LSST/Anaconda/opt/lsst/fftw/lib/
wasabi:walter % setup boost
wasabi:walter % echo $LD_LIBRARY_PATH/
/Users/walter/LSST/Anaconda/opt/lsst/boost/lib/
wasabi:walter %
```

As you can see the last setup completely replaces previous setups.  I am informed that this bug has been fixed in 2.0.1.

**Comment by mjuric** [comment]
@danielsf, I wonder if you could do this one? It should be fairly straightforward, just edit:

https://github.com/mjuric/conda-lsst/blob/master/etc/recipes/eups/meta.yaml

, change 1.5.9 to 2.0.1, reset the build number/string from 7 to 0, run `conda build .` in the eups recipe directory, and upload the tarball(s) (one for each platform) to the dev channel (and rerun 'conda index').

**Comment by mjuric** [comment]
Oh, and then open a PR back to incorporate the changes.

**Comment by danielsf** [comment]
Sure.  Does it have to be EUPS 2.0.1 (as opposed to 1.5.10)?  I'm wondering if we can skirt the user tags problem by not going all the way to EUPS 2.0.1 right now.

**Comment by mjuric** [comment]
@danielsf I'm not sure where the fixes that @cwwalter mentioned were first incorporated. You could try.

**Comment by danielsf** [comment]
According to Tim, EUPS 2.0.1 is the only version usable on El Capitan

**Comment by danielsf** [comment]
EUPS is updated.  PR has been issued.

**Comment by mjuric** [comment]
EUPS recipe has now been bumped to 2.0.2 (on master), resolving both the El Capitan `DYLD_LIBRARY_PATH` issue, and the user tags issue. @danielsf, could you rebuild & publish to `dev` channel (and close this issue once that's done)?

**Comment by danielsf** [comment]
Will do.  I first need to understand why eups distrib install is not properly handling the git-lfs repos in the most recent (read: this weekend) tag of the sims stack.  Once that is under control, I will focus on getting a new conda build out.

**Comment by danielsf** [comment]
I have uploaded eups 2.0.2.

I do not appear to be allowed to close issues on this repo

**Comment by mjuric** [comment]
@danielsf Many thanks!
