### ISSUE TITLE
eups-setups.csh breaks if DYLD_LIBRARY_PATH is not already set

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#55]
eups-setups.csh assumes that DYLD_LIBRARY_PATH already exists.  If it does not, the script fails (at least on OSX).

**Comment by mjuric** [comment]
Fixed upstream (https://github.com/RobertLuptonTheGood/eups/issues/92) and included in EUPS 2.0.2. EUPS recipe bumped to 2.0.2 in 913dce47830ce6e44dd8f568e61919a8c3780201.
