### ISSUE TITLE
conda installing lsst-sims-maf does not automatically conda install eups

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#56]
I _think_ this is different from conda installing lsst-sims (at which point, it is just a dependency issue).  I will investigate

**Comment by mjuric** [comment]
Thanks!

`eups` should be a dependency of every package -- could you send me the output of `conda install lsst-sims-maf` that doesn't install it (so I can check the recipes of those packages)?

**Comment by danielsf** [comment]
Never mind.  I reported the issue based on Steve Ridgway's experience.  I just did

conda install lsst-sims-maf

and got eups + all of the appropriate setup scripts, so I don't know what Steve saw.

Sorry for the noise.

**Comment by mjuric** [comment]
@danielsf It'd be good to follow up with Steve -- it may be that his system is surfacing a bug that we're otherwise missing (and that others may trigger as well). Should I reopen?

**Comment by danielsf** [comment]
Sure.  I will email Steve and cc you.

**Comment by mjuric** [comment]
Closing given no further feedback; reopen if needed.
