### ISSUE TITLE
conda-lsst does not know about LFS

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#57]
I apologize if this is a known bug.  It thought that pull request #49 meant that this was resolved.  Anyway...

I used conda-lsst to build b1971 on my Mac (which has LFS on it anyway).  The build worked.  When I went to do the same build on lsst-dev (which does not have LFS on it), the build failed because conda-lsst did not properly clone the LFS-managed files in sims_maps.

This leads me to believe that the build only passed on my Mac because I had LFS installed, not because conda-lsst knew about git LFS.

**Comment by danielsf** [comment]
actually... I wonder if the dependencies for sims_maps are not properly declared.  Let me check on that.

**Comment by mjuric** [comment]
No, #49 only added the recipe to build git-lfs.

You're right regarding why the build worked on your Mac. I'm working on enabling it even when git-lfs isn't installed.
