### ISSUE TITLE
conda installation of lsst-sims-photUtils deleted conda binary

### ISSUE THREAD

**Issue by rhiannonlynne** [mjuric/conda-lsst#68]
Matthew Graham (@doccosmos) tried to install lsst-sims-photUtils on a mac running Yosemite (10.10.5), with a relatively recent version of anaconda2 (python 2.7.10). 

The install did some terribly bad things, rendering the anaconda installation unusable. He reports it deleted his ~/anaconda/bin/conda binary (and ~/anaconda/bin/python link). 

The instructions he was following to install lsst-sims-photUtils are pretty standard:
conda config --add channels http://eupsforge.net/conda/dev
conda install lsst-sims-photUtils
conda install lsst-sims-maps

I haven't heard of this happening before, but I guess most people install lsst-sims or lsst-sims-maf. 
I tried to reproduce it on my yosemite mac, downloading a new version of anaconda and then doing -
conda install lsst-sims-photUtils
but was unable to reproduce the failure. 

Any ideas? What other information do we need to try to diagnose the problem? 
Rendering anaconda itself unusable is not a desirable outcome.

**Comment by mjuric** [comment]
@doccosmos: was there anything peculiar with your install of Anaconda? E.g., is there anything in [this issue](https://github.com/conda/conda/issues/1685) you may think is relevant to your system?

**Comment by mjuric** [comment]
Also, could you paste the contents of your anaconda2/pkgs directory (we're trying to reproduce the problem).

**Comment by doccosmos** [comment]
Unfortunately I had to wipe the whole old anaconda installation to get a new one in place and so do not have this information any more. One of the tasks conda suggested when I did: conda install lsst-sims-photUtils - was an update of conda itself.

**Comment by mjuric** [comment]
What about https://github.com/conda/conda/issues/1685? Did you ever do any tarball installs, or anything else tha would be out of the ordinary?

Right now my thinking is that this is more likely to be a conda bug than something on our end -- conda is fully in control of the install process. I'd still like to understand what happened.

**Comment by mjuric** [comment]
Also, did you try installing with the new version of Anaconda that you installed after this mess?

**Comment by doccosmos** [comment]
I've never initiated a tarball install myself but it's always possible that conda has done this itself when doing an update. I have not yet tried installing the LSST stuff on the new anaconda - I'll try that tomorrow when I'm back in office.

**Comment by mjuric** [comment]
I'm closing this, assuming it was an upstream Anaconda problem. But do reopen if there's more for us to investigate.
